spring.application.name=Hire-Hub
server.port=9000

#spring.mongodb.uri=mongodb://localhost:27017/hirehub
spring.mongodb.uri=mongodb+srv://Hirehub_Owner:XKXNbsuiZEmdpaqG@cluster0.jjpq19w.mongodb.net/hirehub?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.auto-index-creation=true


# Email Properties

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=panth2711200@gmail.com
spring.mail.password=bxoxkelakoqsgooh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Auhtntication

jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUQXV0aGVudGljYXRpb24xMjM0NTY3ODkw
jwt.expiration=86400000


USER_FOUND = User Already Exists.
USER_NOT_FOUND = User Not Exists.
INVALID_CREDENTIALS = Invalid Credentials.
OTP_NOT_FOUND = OTP Is Expired.
OTP_NOT_MATCHED = OTP Is Incorrect.
JOB_NOT_FOUND = Job Not Found.
JOB_ALREADY_APPLIED = Already Applied For This Job. 